version: '3.8'

services:
  molpi-app:
    build: .
    ports:
      - "8082:8082"
    environment:
      - FLASK_ENV=production
      - PORT=8082
    volumes:
      - ./Python/molpi.db:/app/backend/molpi.db
    restart: unless-stopped
    
  # Opcional: Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - molpi-app
    restart: unless-stopped
