services:
  molpi-app:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - FLASK_ENV=production
      - PORT=8080
    volumes:
      - ./backend/molpi.db:/app/backend/molpi.db
      - ./backend/data:/app/backend/data
    restart: unless-stopped
    
  # Nginx deshabilitado - usando nginx del host
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - molpi-app
  #   restart: unless-stopped
