[build]
  # Directorio donde están los archivos del frontend
  publish = "frontend"
  
  # No hay comando de build porque es HTML estático
  command = "echo 'No build required for static site'"

[build.environment]
  # Variables de entorno para Netlify
  NODE_VERSION = "18"

[[headers]]
  # Para todos los archivos
  for = "/*"
  [headers.values]
    # Permitir CORS desde el dominio de PythonAnywhere
    Access-Control-Allow-Origin = "https://sgit.pythonanywhere.com"
    # Cachear archivos estáticos
    Cache-Control = "public, max-age=31536000"
    # CSP más permisiva para permitir scripts inline y fuentes externas
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net https://code.jquery.com https://maxcdn.bootstrapcdn.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net https://maxcdn.bootstrapcdn.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.pythonanywhere.com"

[[headers]]
  # Para archivos HTML no cachear tanto
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    # CSP específica para HTML con permisos para scripts inline
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net https://code.jquery.com https://maxcdn.bootstrapcdn.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net https://maxcdn.bootstrapcdn.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.pythonanywhere.com"

# Redirecciones en caso de que accedan a la raíz
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
